# Generated by Django 5.2.8 on 2025-11-16 22:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False, unique=True)),
                ('number', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('room_type', models.CharField(choices=[('single', 'single'), ('double', 'Double'), ('suite', 'Suite'), ('family', 'Family')], max_length=20)),
                ('capacity', models.PositiveIntegerField(default=1)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('guests_count', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Oczekująca'), ('confirmed', 'Potwierdzona'), ('cancelled', 'Anulowana'), ('completed', 'Zakończona')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='api.room')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='PLN', max_length=3)),
                ('method', models.CharField(choices=[('stripe', 'Stripe (online)'), ('cash', 'Gotówka / Kasa fiskalna')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Oczekująca'), ('succeeded', 'Zakończona powodzeniem'), ('failed', 'Nieudana'), ('refunded', 'Zwrócona'), ('cancelled', 'Anulowana')], default='pending', max_length=20)),
                ('stripe_payment_intent_id', models.CharField(blank=True, help_text='ID PaymentIntenta w Stripe (dla płatności online)', max_length=255, null=True)),
                ('stripe_charge_id', models.CharField(blank=True, help_text="ID charge'a w Stripe (jeśli używane)", max_length=255, null=True)),
                ('stripe_session_id', models.CharField(blank=True, help_text='ID Checkout Session (jeśli używasz Stripe Checkout)', max_length=255, null=True)),
                ('receipt_number', models.CharField(blank=True, help_text='Numer paragonu z kasy fiskalnej (dla płatności w lokalu)', max_length=100, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='api.reservation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
