# Generated by Django 5.2.8 on 2025-11-17 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_room_reservation_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('guest', 'Guest'), ('staff', 'Staff'), ('admin', 'Admin')], default='guest', max_length=20),
        ),
    ]
