# Generated by Django 5.2.8 on 2025-11-18 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_room_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='room',
            name='updated_at',
        ),
    ]
