# Generated by Django 5.2.8 on 2026-01-27 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_room_created_at_remove_room_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='beds',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('single', 'single'), ('double', 'Double'), ('suite', 'Suite'), ('family', 'Family'), ('multi_room', 'Multi Room')], max_length=20),
        ),
    ]
